---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      # syntax check
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      # whitespaces
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
        exclude: ".config/nvim/lazy-lock.json"
      # scripts/exe
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      # credentials leak
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.0
    hooks:
      - id: yamllint
        args: [-c, .config/yamllint/config]

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.0.2
    hooks:
      - id: stylua-github
        args: [--config-path, .config/nvim/stylua.toml]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: ".config/nvim/lazy-lock.json"

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

  - repo: https://github.com/crate-ci/typos
    rev: v1.31.1
    hooks:
      - id: typos

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: ".config/nvim/lazy-lock.json|.config/clojure/tools/tools.edn"

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.24.3
    hooks:
      - id: gitleaks

  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.9
    hooks:
      - id: ripsecrets
