icons_format = " {icon} "

[theme]
theme = "solarized-dark"

[icons]
icons = "awesome6"

[[block]]
block = "music"
player = "spotify"
format = "{   $combo.str(max_w:20,rot_interval:0.2) $play |}"

[[block]]
# keyboard layout using xkblayout-state from AUR
block = "custom"
interval = 0.1
json = false
command = "xkblayout-state print %s"

[[block]]
block = "cpu"
format = "$barchart $utilization "

[[block]]
block = "memory"
format = "$icon$mem_used"

[[block]]
block = "disk_space"
path = "/"
interval = 5
warning = 15.0
alert = 10.0

[[block]]
block = "bluetooth"
if_command = "systemctl status bluetooth"
mac = "00:0A:45:03:4E:54"

[[block]]
block = "sound"
headphones_indicator = true

[[block]]
block = "backlight"
if_command = '[ -n "$(ls -A /sys/class/backlight)" ]'

[[block]]
block = "weather"
interval = 60
# NOTE: api key and city are set through the envs OPENWEATHERMAP_API_KEY and OPENWEATHERMAP_CITY_ID
service = { name = "openweathermap", units = "metric" }

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%a, %d.%m %T ')"
interval = 1
